---
{{ readFile "../common/templates.yaml" }}
{{- $globalPrometheus := .Values | get "global-config.prometheus" dict }}
{{- $prometheusIngress := .Values | get "prometheus.ingress" dict }}

repositories:

  - name: bitnami-pre-2022
    url: https://raw.githubusercontent.com/bitnami/charts/eb5f9a9513d987b519f0ecd732e7031241c50328/bitnami

  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

  - name: bedag
    url: https://bedag.github.io/helm-charts

releases:

  - name: metrics-server
    <<: *system
    namespace: kube-system
    chart: bitnami-pre-2022/metrics-server
    version: 5.10.13
    needs:
      - monitoring-system/prometheus

  {{- if $globalPrometheus | get "enabled" false }}
  - name: prometheus
    <<: *system
    installedTemplate: '{{ `true` }}'
    namespace: monitoring-system
    chart: prometheus-community/kube-prometheus-stack
    version: {{ $globalPrometheus | get "version" "27.0.1" }}
  {{- end }}

  - name: prometheus-auth
    <<: *system
    installedTemplate: '{{ if and ($prometheusIngress | get "auth.username" false) ($prometheusIngress | get "auth.password" false) }}true{{ else }}false{{ end }}'
    namespace: monitoring-system
    chart: bedag/raw
    version: 1.1.0