---
{{ readFile "../common/templates.yaml" }}

releases:

  - name: metrics-server
    <<: *system
    namespace: kube-system
    chart: bitnami/metrics-server
    version: 5.10.5

  - name: ingress-default
    <<: *system
    namespace: ingress-system
    chart: ingress-nginx/ingress-nginx
    version: 4.0.6

  {{- range $name, $ingress := .Values | get "ingress-multi" dict }}
  - name: {{ $name }}
    installed: {{ default "false" $ingress.installed }}
    namespace: ingress-system
    chart: ingress-nginx/ingress-nginx
    version: {{ default "4.0.6" $ingress.version }}
    values:
      - ./values/ingress-multi.yaml.gotmpl
  {{- end }}