---
{{ readFile "../common/templates.yaml" }}

repositories:

  - name: rimusz
    url: https://charts.rimusz.net

  - name: bitnami-pre-2022
    url: https://raw.githubusercontent.com/bitnami/charts/eb5f9a9513d987b519f0ecd732e7031241c50328/bitnami

  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx

  - name: mlohr
    url: https://helm-charts.mlohr.com/

releases:

  - name: hostpath-provisioner
    <<: *system
    namespace: infra-system
    chart: rimusz/hostpath-provisioner
    version: 0.2.13

  - name: hcloud-cloud-controller-manager
    <<: *system
    namespace: hcloud-system
    chart: mlohr/hcloud-cloud-controller-manager
    version: 3.0.0

  - name: hcloud-csi-driver
    <<: *system
    namespace: hcloud-system
    chart: mlohr/hcloud-csi-driver
    version: 2.0.0

  - name: metallb
    <<: *system
    namespace: metallb-system
    chart: bitnami-pre-2022/metallb
    version: 2.5.16

  - name: ingress-default
    <<: *system
    namespace: ingress-system
    chart: ingress-nginx/ingress-nginx
    version: 4.0.6
    needs:
      - monitoring-system/prometheus

  {{- range $name, $ingress := .Values | get "ingress-multi" dict }}
  - name: {{ $name }}
    installed: {{ default "false" $ingress.installed }}
    namespace: ingress-system
    chart: ingress-nginx/ingress-nginx
    version: {{ $ingress | get "version" "4.0.6" }}
    values:
      - ./values/ingress-multi.yaml.gotmpl
    needs:
      - monitoring-system/prometheus
  {{- end }}