---
{{ readFile "../common/templates.yaml" }}

repositories:

  - name: bitnami
    url: https://charts.bitnami.com/bitnami

  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx

  - name: mlohr
    url: https://helm-charts.mlohr.com/

releases:

  - name: metrics-server
    <<: *system
    namespace: kube-system
    chart: bitnami/metrics-server
    version: 5.10.5
    needs:
      - monitoring-system/prometheus

  - name: hcloud-cloud-controller-manager
    <<: *system
    namespace: hcloud-system
    chart: mlohr/hcloud-cloud-controller-manager
    version: 3.0.0

  - name: metallb
    <<: *system
    namespace: metallb-system
    chart: bitnami/metallb
    version: 2.5.16

  - name: ingress-default
    <<: *system
    namespace: ingress-system
    chart: ingress-nginx/ingress-nginx
    version: 4.0.6
    needs:
      - monitoring-system/prometheus

  {{- range $name, $ingress := .Values | get "ingress-multi" dict }}
  - name: {{ $name }}
    installed: {{ default "false" $ingress.installed }}
    namespace: ingress-system
    chart: ingress-nginx/ingress-nginx
    version: {{ $ingress | get "version" "4.0.6" }}
    values:
      - ./values/ingress-multi.yaml.gotmpl
    needs:
      - monitoring-system/prometheus
  {{- end }}