---
bases:
  - provisioning/repositories.yaml
  - provisioning/clusters/init.yaml

---
helmDefaults:
  wait: true
  timeout: 300
  atomic: true
  cleanupOnFail: true

---
templates:
  default: &default
    missingFileHandler: Warn
    installedTemplate: '{{`{{ .Values | get (printf "%s.installed" .Release.Name) "false" }}`}}'
  system: &system
    <<: *default
    values:
      - provisioning/values/{{`{{ .Release.Name }}`}}.yaml
      - provisioning/values/{{`{{ .Release.Name }}`}}.yaml.gotmpl

releases:

  - name: metrics-server
    <<: *system
    namespace: kube-system
    chart: bitnami/metrics-server
    version: 5.10.5
