---
bases:
  - provisioning/repositories.yaml
  - provisioning/clusters/init.yaml

---
helmDefaults:
  wait: true
  timeout: 300
  atomic: true
  cleanupOnFail: true

---
templates:
  default: &default
    missingFileHandler: Warn
    installedTemplate: '{{`{{ .Values | get (printf "%s.installed" .Release.Name) "false" }}`}}'
  system: &system
    <<: *default
    values:
      - provisioning/values/{{`{{ .Release.Name }}`}}.yaml
      - provisioning/values/{{`{{ .Release.Name }}`}}.yaml.gotmpl

releases:

  - name: metrics-server
    <<: *system
    namespace: kube-system
    chart: bitnami/metrics-server
    version: 5.10.5

  - name: ingress-default
    <<: *system
    namespace: ingress-system
    chart: ingress-nginx/ingress-nginx
    version: 4.0.6

  {{- range $name, $ingress := .Values | get "ingress-multi" dict }}
  - name: {{ $name }}
    installed: {{ default "false" $ingress.installed }}
    namespace: ingress-system
    chart: ingress-nginx/ingress-nginx
    version: 4.0.6
    values:
      - provisioning/values/ingress-multi.yaml.gotmpl
  {{- end }}
