---
{{ readFile "../common/templates.yaml" }}
{{- $globalPrometheus := .Values | get "global-config.prometheus" dict }}

repositories:

  - name: jetstack
    url: https://charts.jetstack.io

releases:

  - name: cert-manager
    <<: *system
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: v1.6.1
    needs:
      - monitoring-system/prometheus
