---
{{ readFile "../common/templates.yaml" }}
{{- $globalPrometheus := .Values | get "global-config.prometheus" dict }}

repositories:

  - name: jetstack
    url: https://charts.jetstack.io

  - name: mariof-charts
    url: https://mario-f.github.io/helm-charts/

releases:

  - name: cert-manager
    <<: *system
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: v1.6.1
    needs:
      - monitoring-system/prometheus

  - name: cert-manager-webhook-hetzner
    <<: *system
    namespace: cert-manager
    chart: mariof-charts/cert-manager-webhook-hetzner
    version: 1.2.1
    needs:
      - cert-manager/cert-manager
    disableValidation: true

  - name: external-dns-hetzner
    <<: *system
    namespace: external-dns
    chart: bitnami/external-dns
    version: 6.0.2
