---
- name: Create VMs
  hosts: all
  gather_facts: False
  connection: local

  tasks:

    - name: Create new VM with minimal options
      community.general.proxmox_kvm:
        api_user: root@pam
        api_password: 
        #api_token_id: ansible
        #api_token_secret: XXXX
        api_host: node03.skynet.local
        node: node03
        name: ansible-testvm
        vmid: 9998