---
- name: Create VMs
  hosts: all
  gather_facts: False
  connection: local

  tasks:

    - name: Create new VM with minimal options
      community.general.proxmox_kvm:
        api_host: "{{ lookup('env', 'PVE_HOST') }}"
        api_user: "{{ lookup('env', 'PVE_USER') }}"
        api_password: "{{ lookup('env', 'PVE_PASSWORD') }}"
        node: "{{ lookup('env', 'PVE_NODE') }}"
        name: ansible-testvm
        vmid: 9998