# Suited and tested for ubuntu-server at this moment
---
- name: Install packages commonly used and required
  ansible.builtin.package:
    name:
      - open-iscsi # often required by storage providers
    state: present

- name: Comment out swap in fstab
  ansible.builtin.lineinfile:
    dest: /etc/fstab
    regexp: '(?i)^(/.*swap.*)'
    line: '# \1'
    backrefs: yes
    state: present
  notify:
    - swapoff
  when: swap_off

- ansible.builtin.include_tasks: replace-dns.yml
  when: replace_dns
  tags:
    - replace-dns

- ansible.builtin.include_tasks: docker.yml
  when: use_docker
  tags:
    - docker
