# Suited and tested for ubuntu-server at this moment
---
- name: Comment out swap in fstab
  ansible.builtin.lineinfile:
    dest: /etc/fstab
    regexp: '(?i)^(/.*swap.*)'
    line: '# \1'
    backrefs: yes
    state: present
  notify:
    - swapoff
  when: swap_off

- ansible.builtin.include_tasks: replace-dns.yml
  when: replace_dns
  tags:
    - replace-dns
