---
bases:
  - ./repositories.yaml
  - ./clusters/init.yaml

---
helmDefaults:
  wait: true
  timeout: 300
  atomic: true
  cleanupOnFail: true

---
helmfiles:

  - path: ./monitoring/helmfile.yaml
    values:
      - {{ toYaml .Values | nindent 8 }}
      
  - path: ./infra/helmfile.yaml
    values:
      - {{ toYaml .Values | nindent 8 }}

  - path: ./services/helmfile.yaml
    values:
      - {{ toYaml .Values | nindent 8 }}
