---
environments:
  testcloud:
    values:
      - ./clusters/defaults.yaml
      - ./clusters/testcloud.yaml
      - ./secure/testcloud.yaml

---
helmDefaults:
  wait: true
  timeout: 300
  atomic: true
  cleanupOnFail: true

---
helmfiles:

  - path: ./helmfiles/monitoring/helmfile.yaml
    values:
      - {{ toYaml .Values | nindent 8 }}
      
  - path: ./helmfiles/infra/helmfile.yaml
    values:
      - {{ toYaml .Values | nindent 8 }}

  - path: ./helmfiles/services/helmfile.yaml
    values:
      - {{ toYaml .Values | nindent 8 }}
