templates:
  default: &default
    missingFileHandler: Warn
    installedTemplate: '{{ .Values | get (printf "%s.installed" .Release.Name) "false" }}'
    disableValidationOnInstall: true
  system: &system
    <<: *default
    values:
      - ./values/{{ .Release.Name }}.yaml
      - ./values/{{ .Release.Name }}.yaml.gotmpl